services:
    filelib.twig.extension:
        class: Xi\Filelib\Integration\Symfony\FilelibBundle\Twig\Extension\FilelibExtension
        arguments: [ @filelib ]
        tags:
            -  { name: twig.extension }
