language: php
php:
  - 5.3
  - 5.4
env:
  - DB=mysql
  - DB=sqlite
  - DB=pgsql

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS xi_filelib_test;' -uroot; mysql -uroot xi_filelib_test < docs/schema-mysql.sql; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then sqlite3 xi_filelib_test < docs/schema-sqlite.sql; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE xi_filelib_test;' -U postgres; psql xi_filelib_test -f docs/schema-postgresql.sql; fi"
  - cd tests && php composer.phar install && cd ..
  - cd tests && wget http://framework.zend.com/releases/ZendFramework-1.11.11/ZendFramework-1.11.11-minimal.tar.gz && tar zxf ZendFramework-1.11.11-minimal.tar.gz && cd ..
  - pyrus install pear.phpunit.de/DbUnit
  - phpenv rehash
  - wget http://pecl.php.net/get/mongo-1.2.7.tgz
  - tar -xzf mongo-1.2.7.tgz
  - sh -c "cd mongo-1.2.7 && phpize && ./configure --enable-mongo && make && sudo make install"
  - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script: cd tests && phpunit --configuration travis/$DB.travis.xml

notifications:
  irc: "irc.freenode.net#xi-project"
